name: 'dbt_extend'
version: '0.1.0'

target-path: "target"
clean-targets: ["target", "dbt_modules"]
macro-paths: ["macros"]
log-path: "logs"


quoting:
    identifier: false
    schema: false

models:
    vars:
        'time_zone': 'America/New_York'